CREATE TABLE `objekte` (
                           `ID` int(11) NOT NULL AUTO_INCREMENT,
    `OBJEKT` varchar(200) DEFAULT NULL COMMENT 'Bezeichnung des Objekts',
    `SYNONYM` varchar(300) DEFAULT NULL COMMENT 'Synonyme fÃ¼r die Objektsuche',
    `POS` int(11) DEFAULT NULL,
    `ORT` varchar(150) DEFAULT NULL,
    `ORTSTEIL` varchar(150) DEFAULT NULL,
    `PLZ` varchar(5) DEFAULT NULL,
    `STRASSE` varchar(150) DEFAULT NULL,
    `HAUSNUMMER` varchar(10) DEFAULT NULL,
    `NUMMER` varchar(15) DEFAULT NULL COMMENT 'Objektnummer (u.a. fÃ¼r die Zuordnung bei BMA-Alarmen)',
    `AAO_GEBIET` varchar(20) DEFAULT NULL,
    `INFO_PFAD` varchar(512) DEFAULT NULL,
    `ANFAHRT` text DEFAULT NULL,
    `HINWEIS` varchar(200) DEFAULT NULL COMMENT 'Besondere Hinweise zum Objekt',
    `OBJEKTINFORMATIONEN` text DEFAULT NULL COMMENT 'Freitext Objektinformationen',
    `TELEFON` varchar(40) DEFAULT NULL,
    `OBJEKTTYP` varchar(20) DEFAULT NULL COMMENT 'Typ des Objekts (z.B. ''Klinik'')',
    `KOORDX` double DEFAULT NULL COMMENT 'Koordinate (X-Wert/LÃ¤nge)',
    `KOORDY` double DEFAULT NULL COMMENT 'Koordinate (Y-Wert/Breite)',
    `MAPICON` varchar(1024) DEFAULT NULL,
    `MAPVISIBLE` smallint(6) NOT NULL DEFAULT 1 COMMENT '1= True 0= False',
    `LASTUSER` varchar(20) DEFAULT NULL,
    `LASTCHANGE` datetime NOT NULL DEFAULT current_timestamp(),
    `KONTAKT` int(11) DEFAULT -1,
    `TYP` smallint(6) DEFAULT NULL,
    `EDPCID` int(11) DEFAULT NULL,
    `EDPCUSER` varchar(50) DEFAULT NULL,
    `sync_uuid` uuid DEFAULT NULL,
    `sync_map` uuid DEFAULT NULL,
    `sync_version` text DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `objekte_pk` (`sync_uuid`)
    ) ENGINE=InnoDB AUTO_INCREMENT=5343 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabelle mit den erfassten Objekten'

